### PR TITLE
First major release for austraits

### PR DESCRIPTION
**Pull request by fontikar**
Major features:
* Added vignettes 
* Added Pkgdown
* Scientific labelling for plot_beeswarm
* Functions for joining details and loading data
* Bugs fixed for pivot_

### CODE REVIEW

**Review by dfalster — APPROVED** [review]
Hi Fonti. Looking good! Sorry for the slow review.

I've just pushed some updates. Can you also

- check the changes to load_austraits. It now uses http package. So do we put that in DESCRIPTION?

After that you're fine to merge into master

**Comment by fontikar** [comment]
I've pushed the recent changes (4e98959) and load_austraits is now working (just need to write a test!). everything passed checks but package is now 13mb (not suitable for CRAN) because the structure RMDs downloads the latest austraits build (large list) to report the number of unique species is found in austraits. I am not sure if package size is something we want to minimise? Do we want to submit it to CRAN? 

Currently the 3.0.2 build is stored in inst/extdata/ but maybe I should sort it internally? as in R/sysdata.rda so it doesn't it exported (https://r-pkgs.org/data.html#data)? Will try this method today!

**Comment by dfalster** [comment]
> I've pushed the recent changes (4e98959) and load_austraits is now working (just need to write a test!). everything passed 
great!

> checks but package is now 13mb (not suitable for CRAN) because the structure RMDs downloads the latest austraits build (large list) to report the number of unique species is found in austraits. I am not sure if package size is something we want to minimise? Do we want to submit it to CRAN?
Yes, we want it on CRAN and also to be small. 

I'm starting to thinking the structure info should be in austraits.build or zenodo, not here (or if it is, just on pkdown website, not in the package)

> Currently the 3.0.2 build is stored in inst/extdata/ but maybe I should sort it internally? as in R/sysdata.rda so it doesn't it exported (https://r-pkgs.org/data.html#data)? Will try this method today!
Actually, this maybe where the size comes from, not Structure Rmd. 

We don't want to include 3.0.2 in the package itself, so need to revisit this. 

Maybe best to talk and clarify options

**Comment by fontikar** [comment]
I have temporarily resolved the package size issue in 48d51c2 no storage of 3.0.2, just using load_austraits and setting the path to ignore/ so that nothing is exported with the R package! Should be all good to merge into master! Just need an OK!

**Pull request merged**
