### PR TITLE
Changes for v5 austraits.build

### PR DESCRIPTION
**Pull request by fontikar**
Working with @ehwenk to update functions so they work across all versions of AusTraits. 
- Update to the switches for trait_pivot, extract_ join_ functions. 
- Update to what_version function
- Added dplyr::all_of due to their soft warning deprecation
- Updated internal testing data

R CMD check still gives 1 x  NOTE but I want see if I can deal with these later and if GitHub Action will be unhappy with me

### CODE REVIEW

**Comment by fontikar** [comment]
Zenodo is currently down so some tests will fail...

**Comment by fontikar** [comment]
I am a bit confused with .data$ usage now! Passing locally when I use .data$ throughout functions, but tidyselect throws warnings in GitHub Action R CMD check

**Comment by fontikar** [comment]
> I am a bit confused with .data$ usage now! Passing locally when I use .data$ throughout functions, but tidyselect throws warnings in GitHub Action R CMD check

Less confused now after reading this: https://community.rstudio.com/t/use-of-data-in-tidyselect-expressions-is-now-deprecated/150092

**Comment by fontikar** [comment]
Bah! I can't get this passing with all the tidyselect stuff. Will look on Monday!!! Assistance would be great if someone knows what I am doing wrong

**Comment by fontikar** [comment]
@dfalster over to you :D

**Comment by yangsophieee** [comment]
Sorry for touching this branch! I was trying to get `austraits` functions to work as I'm testing them on traits.build. I've reverted my commit which was failing R CMD check but it's still failing now so I'm not sure what happened.

@fontikar When you're back I'm happy to look through tidyselect warnings as I had to remove them for traits.build so might have an idea where they're coming from.

**Comment by yangsophieee** [comment]
Also my changes were wrong, it was fine as is!

**Comment by fontikar** [comment]
@dfalster all good to merge this??

**Review by dfalster — APPROVED** [review]

**Comment by dfalster** [comment]
Please coordinate with @ehwenk @dcol2804  as they're using it

**Comment by ehwenk** [comment]
@fontikar The austraits.build tutorial that uses the functions is rendering. But maybe wait 1-2 hours until I've finished going through it line by line?

**Comment by fontikar** [comment]
Sounds good no worries! I reran tests locally and all passing so its _should_ be smooth sailing from here

**Pull request merged**
