### PR TITLE
Major upgrades to {austraits}

### PR DESCRIPTION
**Pull request by fontikar**
A major feat from all of us but especially @ehwenk! 👏 🎉  thank you for working so tirelessly in refactoring and building more user-friendly functions! 

As discussed in #92, the goal of this upgrade was to: 

1. Discontinue support for AusTraits version < 4.2.0
    - Mass removal of switch functions that controlled function behaviour depending on AusTraits version #102, 91
    - Creation of `check_compatibility()` #100
    - Console messaging alerting user which version of AusTraits is supported by which functions #100
    - Updated documentation guiding user on how to install an older version of the R package for backwards compatibility #93

2. Introduce new `traits.build` 'wrangling output' functions into `austraits`
    - `flatten_database` added to `austraits` #105
    - `bind_databases` added to `austraits` #106
    
3.  Reduce redundancy across `traits.build` and `austraits` to streamline codebase maintenance 
    - `plot_trait_beeswarm` moved back to `austraits` 
    - `trait_pivot_` moved back to `austraits`
    
4. Refactor {austraits} functions to support other `traits.build` databases and allow functionality across more tables and columns.
    - `join_` functions  #91 
    - `extract_` functions #107
        - `extract_data`
    - Rename argument names #115
   
5. Update documentation accordingly
    - Pointing to APD and traits.build-book directly in README and vignette #96 #74 
    - Added cheatsheet

### CODE REVIEW

**Review by dfalster — CHANGES_REQUESTED** [review]
Amazing work @fontikar @ehwenk. I'm very glad we handled this in several branches off develop, instead of one monster changeset. So I'd approved on the basis that we've reviewed it all before. 

One request. Codecov is alerting me to several lines that have escaped testing. Can you add more tests to cover these? Feels like now is the time, while codecov is pointing them out.

**Comment by dfalster** [comment]
if you scroll through the changes, you see alerts like this

Screenshot 2024-11-18 at 11 37 29 AM

**Comment by fontikar** [comment]
> if you scroll through the changes, you see alerts like this
> 
> Screenshot 2024-11-18 at 11 37 29 AM

Good point! Lizzy and I have divided up the functions where `codecov` has flagged tests are needed

I think some are a bit strange like this one for `load_austraits` where changes from native pipe to magrittr pipe is not captured by tests... 


Screenshot 2024-11-18 at 1 16 28 PM

**Comment by dfalster** [comment]
This could an indicator that this line was never tested in the first place.

**Review by fontikar — COMMENTED** [review]
This looks great! I think we are ready for the merge!! Well done team!!

**Review by dfalster — APPROVED** [review]

**Pull request merged**
