### PR TITLE
Join site plot

### PR DESCRIPTION
**Pull request by dfalster**

### CODE REVIEW

**Comment by fontikar** [comment]
Yikes. I didn't merge immediately into master instead developed the joining suite on this branch and now ready to pull it into master! Will fix the conflicts now!

**Comment by fontikar** [comment]
All done! Now I need tests for plot site locations!

**Comment by dfalster** [comment]
Super! As discussed, it's perhaps enough to just check the plot code runs without error. I don't know if you can test the actual plot layout.

**Comment by fontikar** [comment]
It might be possbile but we are working with a ggtable/grob so I can play around but so far it is just being tested to return silently. 

https://stackoverflow.com/questions/31038709/how-to-write-a-test-for-a-ggplot-plot

**Pull request merged**
